name: Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install dependencies (if any)
      - name: Install dependencies
        run: |
          npm install

      # Step 3: Build the static site (if applicable)
      - name: Build static site
        run: |
          npm run build

      # Step 4: Deploy the static site
      - name: Deploy static site
        run: |
          echo "Deploying the static site..."
          # Add deployment commands here, e.g., uploading to a hosting service