name: Deploy Static Site
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the static site
      - name: Build static site
        run: npm run build

      # Deploy the static site to the hosting platform
      - name: Deploy static site
        env:
          HOSTING_PLATFORM_API_KEY: ${{ secrets.HOSTING_PLATFORM_API_KEY }}
        run: npx hosting-cli deploy