name: Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        npm install

    - name: Build static site
      run: |
        npm run build

    - name: Deploy to Hosting Platform
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: |
        npx netlify deploy --prod --dir=build

    - name: Notify Deployment Success
      if: success()
      run: |
        echo "Deployment successful!"