name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Static Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Prepare Static Files
        run: |
          mkdir -p build
          cp -r ./* build/

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_branch: gh-pages
