name: Static Site CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  validate:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate HTML files
        run: |
          npx htmlhint "**/*.html"
      - name: Validate CSS files
        run: |
          npx stylelint "**/*.css"
      - name: Validate JavaScript files
        run: |
          npx eslint "**/*.js"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build static site
        run: npm run build
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist