name: Static Website CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  link-checker:
    name: Link Checker Test
    runs-on: ubuntu-latest
    steps:
      # Step to checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Step to run the link-checker tool
      - name: Run Link Checker
        run: |
          npx link-checker ./index.html

deploy:
    name: Fast Deployment to GitHub Pages
    runs-on: ubuntu-latest
    needs: link-checker
    steps:
      # Step to checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Step to deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Assuming the static files are in the root directory